name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env: 
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN}
        docker build . --file=Dockerfile --tag wjdalsckd45/gdsc-tuk-fe:${GITHUB_REF_NAME}
        docker push wjdalsckd45/gdsc-tuk-fe:${GITHUB_REF_NAME}
